### ISSUE TITLE
Breaking pad

### ISSUE THREAD

**Issue by setsunafseiei** [jrddunbr/ElectricalAge#147]
I would like to request for a breaking pad for stopping the rotation of the system instantly without placing additional block

**Comment by setsunafseiei** [comment]
especially waiting for the flywheel to stop rotating

**Comment by jrddunbr** [comment]
We have the clutch and the fixed shaft. If you want to stop it without placing anything, break the block.

**Comment by Grissess** [comment]
Do note that the "placing an additional block to stop the shaft" was (1) unintended behavior and (2) causes explosions in the version of the mod where the clutch and fixed shaft were introduced. Aside from that, yes, those two blocks are heavily recommended as brakes in any shaft network :)

Clutches don't stop networks _instantly_, but they are arguably too strong at the moment and can probably stop even large flywheel networks within a few ticks. Let me know if you somehow exceed that limit. (Also, don't forget to install a clutch plate!)

**Comment by jrddunbr** [comment]
They are very OP, yes. The pads also last a VERY long time and can handle large loads that would probably turn most metals into molten metal. I've put MW of power into a shaft network before just to stop it against a single clutch.

**Comment by GrimmDemon** [comment]
I'd like to add. I was fooling around after reading this and decided to build a shaft network of a couple hundred flywheels, approximately, 11x11x3, and gave it a test.
It was a pain to get it to 1kRad/s and I used 4  clutches, playing with different clutch plates every run. The iron plate was terrifically slow to stop, same with the gold plate, the copper plate was adequate, and lead plate was remarkably good, although it melted the fastest, probably because lead is a soft metal anyways. I did try the coal clutch plate, but it exploded as I activated the clutch, leaving me with Mega-Jouls of energy left in the flywheel system, I wonder if the coal plates are buggy in any way or are they just too OP?

**Comment by jrddunbr** [comment]
You have been sniped. Do you realize what would happen if you put coal in a real clutch?

**Comment by jrddunbr** [comment]
To be more specific:

https://github.com/jrddunbr/ElectricalAge/blob/base/src/main/java/mods/eln/registry/ItemRegistry.java#L1773-L1778

https://github.com/jrddunbr/ElectricalAge/blob/base/src/main/java/mods/eln/mechanical/Clutch.kt#L34-L38

**Comment by GrimmDemon** [comment]
I take it. If you put coal in a clutch, it'll be crushed, get stuck everywhere and ruin the entire clutch. 😅That's a sneaky way of adding an easter egg. Not to mention all of the blocks I blew up trying to get the coal clutch plate to not blow up 😂

**Comment by GrimmDemon** [comment]
Funny enough. The copper plate was able to negate 98 MJ of rotational power and then some. The lead plate didn't even manage a third🤣

**Comment by Grissess** [comment]
Bugs abound; I suspect I wrote that code and promptly forgot about it :P

A careful reading of `ClutchPostProcess` at [this line](https://github.com/jrddunbr/ElectricalAge/blob/base/src/main/java/mods/eln/mechanical/Clutch.kt#L264) says that you can get a coal plate to synchronize normally if the angular velocity difference is not greater than 5 rad/s (honestly, that number is a bit low). In that case, coal is still one of the worst plates to use in terms of its friction (transfer function) and longevity :P

The difference between copper and lead might be a bug? It's been a while since I fiddled with those numbers on an extremely provisional basis.

**Comment by GrimmDemon** [comment]
I just had an excellent idea. What about a carbon clutch? Cars use them as brake pads and they do have quite a bit of friction and longevity. I know that carbon is quite close to coal, but it's more robust, so that could be useful if you want to use it as a shaft brake.

**Comment by GrimmDemon** [comment]
OK. Technically. Carbon is like diamond. Haha, what about a diamond clutch?

**Comment by jrddunbr** [comment]
Heh, it's all @Grissess fault :D If you work hard enough, you may even guilt him into fixing #156

**Comment by GrimmDemon** [comment]
I still think that the coal clutch plate should be replaced with a carbon one, even it's just the name, and the recipe remains the same. It just makes more sense, in my opinion.

**Comment by jrddunbr** [comment]
We're probably not adding more clutch plates for a while.
