### ISSUE TITLE
adjusting maximum rad/s

### ISSUE THREAD

**Issue by setsunafseiei** [jrddunbr/ElectricalAge#149]
i would like to request the maximum rad/s of the rotation to be configurable

**Comment by jrddunbr** [comment]
In what ways and why? I'm going more for realism than configurability, and those need to be highly tuned for the mod to be well balanced. To be fair, the current motor and generator limits aren't 100% there (I blame the current thermal system), but we spent a lot of time around the time of the shaft update setting up the spin-up curves and such, and it's mostly catered for the speed, weights, and power that the mod has. If you want to run them slower, feel free, but I will not be increasing the maximum speed on the shafts.

That said, I may lower the speed requirement for gas turbines and in general, might lower the rad/s to voltage ratio to make more volts at higher rad/s than currently is in place.

Don't forget either - rad/s is quite a bit lower numerically than the related RPM - 1000 rad/s is about 9550 RPM, which is pretty fast for most rotary devices out there. Most stuff would run closer to 350-375 rad/s for the faster motors. Here's some IRL motors from a catalog to reference from:

[SpecGuide.pdf](https://github.com/jrddunbr/ElectricalAge/files/3292357/SpecGuide.pdf) ([source](https://www.baldor.com/~/media/files/brands/baldor-reliance/resources%20and%20support/specguide.ashx))

**Comment by setsunafseiei** [comment]
thanks for the note

**Comment by Grissess** [comment]
There's no reason it can't be configurable. [Here](https://github.com/jrddunbr/ElectricalAge/blob/base/src/main/java/mods/eln/mechanical/ShaftNetwork.kt#L20)'s where that constant is right now.

The same source file has plenty of other parameters which might be useful to twiddle, though @jrddunbr's right about the game balancing aspect, since not all of them have sensible interdependency. In particular, for example, [here](https://github.com/jrddunbr/ElectricalAge/blob/base/src/main/java/mods/eln/mechanical/Turbines.kt#L37) is one place where such a dependent value is used. Similarly, the [turbine descriptors](https://github.com/jrddunbr/ElectricalAge/blob/base/src/main/java/mods/eln/mechanical/Turbines.kt#L75-L106), which are the main energy input to shaft networks, have some [nonlinear math](https://github.com/jrddunbr/ElectricalAge/blob/base/src/main/java/mods/eln/mechanical/Turbines.kt#L127) involved in computing their efficiency, and this also puts them at odds with the [other hardcoded constants](https://github.com/jrddunbr/ElectricalAge/blob/base/src/main/java/mods/eln/registry/TransparentNodeRegistry.java#L227) for "nominal" settings...

The point is: a lot of work has to be done to make it reasonable to configure that way. Otherwise, it'll probably just explode--and you get to keep the pieces.

**Comment by jrddunbr** [comment]
This probably won't happen.
