### ISSUE TITLE
Shaft clutch

### ISSUE THREAD

**Issue by Grissess** [jrddunbr/ElectricalAge#15]
Used to connect and disconnect rotational systems.

The clutch won't be able to immediately resolve speed differences; rather, it will rely on a fairly standard static/dynamic frictional model: if there is a difference in angular velocity, it will correct it by passing some amount of energy from the high w side to the low w side, with some losses due to inefficiency ("to heat"). If the two are at the same speed, it will be able to transmit energy from one side to the other, up to a maximum, at which point it will begin slipping and resume the former. As in typical textbook frictional models, the maximum energy that can be passed from one shaft to another while not slipping should be higher than the value nominally passed while slipping.

For added realism, add a wear item (like a brake pad) whose wear linearly factors into both limits above.

**Comment by jrddunbr** [comment]
I have a few ideas: (not needing to be implemented soon)

First, here's some IRL materials

https://www.phoenixfriction.com/t-clutch-materials-explained.aspx

We already have a lot of different metal plates. Those could be allowed to be put into the clutch with varying levels of success:

* `copper plate`: wears down easily
* `iron plate`: wears down at a slower rate than copper
* `gold plate`: binds up and doesn't work
* `lead plate`: binds up and doesn't work
* `silicon plate`: creates smoke and works well briefly, then burns up and doesn't work
* `alloy plate`: works decently
* `coal plate`: explodes! (this should be gated by a config option?)

In addition to these:

* `basic braking plate`: crafting is rubber and iron, shapeless recipie (or machine)
* `good braking plate`: crafting is rubber and alloy ingot, shapeless recipie (or machine)
* `ceramic braking plate`: crafting is rubber, alloy ingot, and silicon dust, shapeless recipie (or machine)

On top of all of these thoughts, we could make a new machine that makes pads over a certain grade. Perhaps anything that is a braking plate has to be created in a rotary press (attaches to shaft network) - which requires lower grade plates to operate the devices internal clutch :)

My other thought - generally, clutches are actually made of three components. Make it so that there are two clutch plates and the actual plates mentioned above in the middle.

**Comment by jrddunbr** [comment]
Oh, also. Clutch plates currently say hold shift and have no text under that. Probably not a problem :/

**Comment by Grissess** [comment]
Holding shift in my branch tells you the condition, using the same strings (and translations) as lamp bulbs :) . I'm not sure if my most recent work is pushed, though...

The current clutch plate recipe is three iron ingots, three rubber in two adjacent vertical lines (left and right respectively). You're right, the plate recipes might advance the tiering adequately, and introduce the possibility of multiple materials. I have not yet confirmed that wear is working as anticipated (I have four motors on my test world grinding against a full-closed clutch vs. a fixed shaft, it seems to be holding the same speed despite theoretically transferring less power), but that is also to be taken into account. Currently, these constants are part of the ClutchElement/ClutchProcess, and could be parameterized instead on the items themselves.

I'm not sure about adding the recipes for plates that just don't work; they'd be good for a one-off joke, and that's about it--aside from maybe SMP trolling.

...am I getting the suggestion that the clutch should have two items in it: a braking plate, and a receiving plate? I'm suddenly getting the sense that that's where you're going :)

**Comment by jrddunbr** [comment]
Those plates already exist in game. I was just suggesting that some of them
work as expected and that while some of them are square item fits in square
hole mentally that they behave as expected :)

Yes, I am suggesting a clutch sandwich. The middle plate is what wears the
most, the outer plates wear as well but should take weeks rather than days
(per scale)

You have not pushed the newest stuff is my suspicion. Fixed shafts were not
functioning in the version I cloned.

**Comment by Grissess** [comment]
Ah, right! I'm delaying a push until I get a more satisfactory "plate slipping" sound. I think I'm going to have to go well outside the box on this one, such as "car engine turning over", with some editing to satisfaction :/ . I'm doing my best to keep (any more) useless large binaries in the repo history... but I can make a commit if you really want it; the current clutch sound is a loop-compatible recording of bad bearings on an '01 Accord's AC unit (not mine, fortunately :P)

**Comment by jrddunbr** [comment]
Hmm. Put it up somewhere I guess and I'll take a listen. I'll be on the lookout as well.

**Comment by Grissess** [comment]
Pull `devel-shaft-objects` :)

**Comment by jrddunbr** [comment]
![2018-08-17_17 12 26](https://user-images.githubusercontent.com/14130505/44289084-c3b7a800-a240-11e8-8ed5-2ff8ba4fe28a.png)

The left side of the shaft should probably have oo mass and no rad/s

**Comment by jrddunbr** [comment]
Hmmm, very exciting. There appears to be a bug where a shaft clutch can decide that one of the shafts is allowed to rapidly accelerate to above 1000rad/s, with obvious consequence. Tested with a generator from stop and a already started flywheel to 400rad/s.

**Comment by jrddunbr** [comment]
Technically, it should not have been possible since energy was not being introduced into the system besides stored potential energy of the rotating flywheel.

**Comment by jrddunbr** [comment]
Oh, also. Sound presists from the clutch even when the speeds are the same and it registers as not slipping. Not sure what that is. Tested between two flywheels, one stopped, one at speed, no power introduced.

**Comment by Grissess** [comment]
Yeah, adding sound and a part of the clutching process that allows the two speeds to meet in the middle (arithmetic average) seems to have induced that bug just last night. I suspect a sign error :)

I'll hack on that soon--try to see what conditions reproduce it, if you have time!

**Comment by jrddunbr** [comment]
More features to add.

**Comment by Grissess** [comment]
Namely, different plates, surfaces, etc.?

The features here shouldn't be conflated with #61, which is also open :)
