### ISSUE TITLE
Generator / Shaft Motor explodes

### ISSUE THREAD

**Issue by setsunafseiei** [jrddunbr/ElectricalAge#153]
Generator / Shaft Motor explodes after setting voltage (electrical source) from 2kV to 0V. is it a bug or it is designed like that?

**Comment by setsunafseiei** [comment]
nevermind
i shouldn't use electrical source

**Comment by Grissess** [comment]
It used to be the case that they didn't; nowadays, they handle temperature correctly. They have the thermal characteristics of a VHV cable--and can overheat the same way. Don't do that :)

**Comment by GrimmDemon** [comment]
If I may add here. I noticed that once the voltage from something that is connected to the creative voltage supply exceeds the voltage specified on the voltage supply, is basically becomes a grounding pin of some sort, especially of you set the voltage to 0.
But that's common knowledge given voltage does travel from the highest point to the lowest point in the circuit, be that a consumer (which is automatically grounded) or an electrical producer. The voltage on the electrical source does, however, limit the current into it slightly, mainly when the two voltages are somewhat similar, but yeah, still somewhat a grounding pin.
I'm trying to use that thing less these days because of the explosions that I get from the unlimited power it can put out, it's handy to start a shaft motor (also likely to blow up) directly next to it, but not when you have multiple connected via cables that are highly likely to blow up.

**Comment by jrddunbr** [comment]
Voltage tends to do that, yes. There may be an unusual amount of instability caused by InterSystem, but running a motor at 12 volts then driving it to 0 with a load on the motor will certainly have that effect IRL. The voltage sources in-game can source far more current than say a battery IRL.

The voltage sources have a very small resistor in them. So do the motors, generators, and honestly most other devices. It's to prevent NaN's and stuff.
