### ISSUE TITLE
Add customizable transformers to poles

### ISSUE THREAD

**Issue by mario2582** [jrddunbr/ElectricalAge#169]
Add T1 Poles with customizable transformers

**Comment by jrddunbr** [comment]
The way that transformers bring down the voltage IRL doesn't quite line up with how it works for DC.

That said, configurable transformers is planned.

**Comment by GrimmDemon** [comment]
It would be nice if we could play around with AC in electric age. AC is a rather peculiar way of transmitting electricity, given the fact that it's always changing, based on the frequency of course. I can imagine if there was AC and DC in electrical age, certain things will only run on DC and others in AC, for example, fluorescent tubes can run on both AC and DC, but their chokes are only effective using AC and if they do use DC, they burn out faster because the electrons are flowing in one direction only, AC doesn't do this because each side of the tube is being equally used, especially at the higher frequencies adopted in the CFLs which sit at 10kHz.
BTW: I'm using minecraft 1.12.2 now, will ELN be compatible with 1.12.2 or only 1.12?

**Comment by jrddunbr** [comment]
No. We will not be supporting AC.

https://wiki.electrical-age.net/index.php?title=FAQ

1.12.2 probably. I don't think there are major differences between the minor versions, but by the time we have it ported everyone will probably be playing Minecraft 1.15

**Comment by jrddunbr** [comment]
Oh, and voltage tiers are going away, so don't even think about offering that it should go to 50v. That's just silly.

**Comment by jrddunbr** [comment]
This issue is being closed now since there will be no more feature updates in Electrical Age for Minecraft 1.7.10.
If the issue is relevant to 1.12, it will be re-opened there at a later date.
