### ISSUE TITLE
LLv12-Dev4 jar file missing

### ISSUE THREAD

**Issue by setsunafseiei** [jrddunbr/ElectricalAge#182]
How to I download the lastest Dev4? Missing Download jar file

**Comment by jrddunbr** [comment]
I removed it because the version is too unstable and I have some serious rewriting to do before it is. I'm encouraging people to use 1.15.3 because it's more stable.

I have 1.17.x on my laptop, (far newer than dev4) but haven't released that either, because it's absolutely guranteed to corrupt worlds.

New versions are a few months out but will be pretty stable compared to now.

**Comment by setsunafseiei** [comment]
Sure thank you
