### ISSUE TITLE
Light bulb / and fixture overhaul for Future Versions of EA

### ISSUE THREAD

**Issue by mario2582** [jrddunbr/ElectricalAge#186]
Something that should be done is a overhaul of Light bulbs and light fixtures for Future Versions of EA

some things that should be changed / updated

- Certain Fixtures can have their internal components altered to retrofit them to run LED tubes or  not and they use plug and play High bay led bulbs.

- Different Kinds of Light-bulbs like HID bulbs like metal halide, Mercury vapor, and HP and LP sodium bulbs, led corn bulbs, fluorescent tubes, CFL's, A19 (standard 60 and 100w light bulbs and equal LED's) BR and PAR Bulbs (Recessed Can Bulbs) MR16 (Track light bulbs), Globe (bathroom fixture bulbs), and Candelabra (chandelier bulbs) fixture wise they all don't fit in one kind of fixture, some like the fluorescent tube only fit in a fluorescent fixture and need a ballast. Most bulbs run off line voltage and fit in most fixtures, the corn bulb easily fits in keyless lamp holders or fixtures big enough to hold and support one. some bulbs are brighter such as the corn bulb will be far brighter than a 100w equal led.

- different and more kinds of light fixtures such as fluorescent and dropped ceiling fluorescent fixtures you would find in your home or a building, stand and table top lamps, chandeliers, ceiling fans w/lights, recessed cans, keyless lamp holders, track lights, flush mount lights, dusk to dawn lights, high bays, low bays, flood lights, and more.

- some bulbs should operate at higher voltages such as HID bulbs light metal halide, MV, and HP Sodium requiring several thousands of volts from a ballast and starter to ignite. same with fluorescent tubes and fluorescent fixtures. also if you stick a fluorescent tube into a flourscent fixture wired for direct wire led tubes, the florescent tube should burn out instantly and pop a breaker if wired properly.

- some fixtures like the high and low bays should have the option of multiple taps to draw more amps at lower voltages and run on normal house wiring voltages and also be able to be wired on a different tap for higher voltages that would require less amps. LED highbays should have built in components to run any voltage supplied up to a max amount like 240v or 480v

- certain lamps like most HID lamps, led lamps, florescent lamps etc should not be dimmable without special components. 

- Design some way to simulate proper dimming in different types of bulbs and different dimmers such as Standard and LED dimmers etc. LED bulbs should dim down to nearly going out while incandescent should totally go out, some dimmers could allow you to set the low end trim (how far down the low end of dimming goes) since some in real life do that. **I don't want to hear any replies about "you can make dimming work in current versions of EA with rheostats etc."** dimming with rheostats in current versions of EA is very finicky and hard to do when you add more lights to a circuit or use a different wattage bulb.

~ _If you Build it... Electricians will Come!_

**Comment by jrddunbr** [comment]
If you're going to continue to be condescending about the answers we give, I'm going to just close all of your issues before reading them.

A lot of the material here has been duplicated in requests on both this issue tracker and the Electrical Age upstream issue tracker. (#167, #178 for example). I don't see the value in adding like 10 different kinds of lights unless ***you*** want to 3D model them. We already have ~5 options, and there are 3 more planned ones as it stands.

Since this issue adds nothing useful except you being annoyed that we don't think dimmers are a sensible addition to the mod because there are other realistic ways to control the lights, I'm just going to close this.

PS. We're adding adjustable DC/DC converters in the 'near' future (aka, a while). Input a signal, control the voltage output. That's about as close as you get to the more modern dimmer circuits.

**Comment by GrimmDemon** [comment]
I'm going to be blunt here. This is GitHub, you should not request large volumes of content, such as the bulbs you mentioned, without putting in your own fair share of effort. Plus, it's best not to doubt the author of the mod/application, because they know what they are doing, you may think that adding features is easy, but it's not, for each feature added, there's a plethora of bugs that need to be sorted out in order for it to run smoothly, not to mention getting all of the calculations correct. I don't know coding, so I don't have room to complain, I do what I can and report bugs and small errors.

**Comment by GrimmDemon** [comment]
Plus, just to enlighten you. Dimmer switches are basically serial variable resistors (varistor) and the reason why LEDs and CFLs do not work on them is that they rely on resisting the current, thus, inadvertently causing the voltage to drop, LEDs and CFLs DO NOT draw enough current to be effectively dimmed.

**Comment by jrddunbr** [comment]
A lot of the dimmers out there actually use a basic analog PWM style circuit with a SCR - it's really just an inductor-capacitor RLC pulse circuit controlled by the resistance of a small rheostat with a low control current, rather than using a dedicated PWM chip (saves cost probably).

The reason that LED's don't work well on these old dimmers is because the frequency of these dimmers turning on and off is very slow - and can be seen as flickering with an LED. With a typical filament based bulb, this is not as easy to notice because the thing is so hot that even with no current going through it, it's still emitting (some) light because it's still warm. Some special LED bulbs can work around this by using a capacitor to provide power for that low state, but I'm not sure how good that is for the dimmer. Others use a fluorescent coating to make the bulb appear to flicker less.

Modern LED dimmers are faster PWM type dimmers that use frequencies probably in the kHz or higher which are not visible to the human eye. I'm sure they are more expensive to make.

-----

Regardless of all of this, both styles of dimmers are too high frequency to simulate in the game, and I also don't plan to give people light-activated seizures by flickering their screen at 30Hz or something silly to that effect.

I've proposed plenty of solutions in past comments, and the best solution is to make a circuit to lower the voltage yourself, since all of the light brightness' in Eln (realistic or not) are controlled by the input voltage. You can do this with a rheostat to increase the resistance and make a voltage divider, or you could use some other parts like a DC/DC converter, some capacitors, or other things to that effect.

In the future, I intend to make an adjustable DC/DC converter that takes a variable voltage in, and a (relatively) stable voltage out. This could potentially make some interesting properties that result in a very simple dimmer circuit design.

**Comment by jrddunbr** [comment]
See new release, 1.15.8, for variable DC/DC converter which acts similarly to a dimmer.
