### ISSUE TITLE
Add Electric Fans and Air ducting

### ISSUE THREAD

**Issue by mario2582** [jrddunbr/ElectricalAge#201]
Add Electric Fans and air ducting

Types of Fans to start with (there are MANY more kinds than this,,,)

- Exhaust Fan
![Wall_Exhaust_Fan_Shutter_Mount_SEF](https://user-images.githubusercontent.com/11165643/71382310-60acf280-25a5-11ea-911c-fb32cc3f3736.jpg)

- Industrial Ceiling Fan
![31RL1sn3sAL _SY355_](https://user-images.githubusercontent.com/11165643/71382313-64d91000-25a5-11ea-9ca7-0b266dd9c12e.jpg)

- Industrial Pedestal Fan
![81OjTFpYHxL _AC_SX679_](https://user-images.githubusercontent.com/11165643/71382321-71f5ff00-25a5-11ea-85b5-1c84861178d2.jpg)

- Industrial Wall Mounted fan
![258321](https://user-images.githubusercontent.com/11165643/71382331-7de1c100-25a5-11ea-8aec-0617a2a9cd17.jpg)

- Barrel Fan
![24876inuse1_27299](https://user-images.githubusercontent.com/11165643/71382344-8b974680-25a5-11ea-92ba-ddba44928e47.jpg)

- Roof Fan
![36inch-50inch-Roof-Mounted-Industrial-Exhaust-Fan](https://user-images.githubusercontent.com/11165643/71382345-90f49100-25a5-11ea-875d-66ccf890294a.jpg)

- Air Ducting
![SET-1](https://user-images.githubusercontent.com/11165643/71382520-53dcce80-25a6-11ea-9005-d09e4f96c70e.jpg)

I have a long term idea for this that would make industrial ventilation and fans useful for more than just looks. Let's start by just modeling and animating and implementing them to work with wiring for the looks and aesthetics in an industrial / power plant type setting electrical build.

my long term idea was to be able to have certain things in EA generate noxious gases (you can make gases by coding custom liquids through the forge fluid coding API for liquids.

The following Coding from forge is how you make a custom fluid a gas so it flows upwards,

public class CustomGasFluid extends Fluid {
public CustomGasFluid() {
	super("gas_fluid");
	setDensity(-100);
	setViscosity(1000);
        setGaseous(true); // **This line here makes the fluid a gas**
	FluidRegistry.registerFluid(this);
}}

Once you implemented custom gases such as creating Carbon Monoxide and smoke from burning coal or fuel to run a turbine, you could code fans to be able to move and push gases such as ones that rose to the ceiling through them and outside where the gases would go away, This would make it so you needed air ducting connected to ventilation fans or exhaust fans in the roof or walls of a powerplant fuel-burning room to remove and exhaust the toxic poisonous gases created.

some other ideas I had for fans are

- Like a wind turbine, when not powered and in an area where high wind could hit the blades, the blades could spin backwards generating a tiny amount of voltage (less than 1 volt) and a very tiny amount of amperage (not even 10 milliamps) on the wire that powers them. Someone up to a big challenge could create a power plant using only fans if they were crazy enough with thousands and thousands of them set up in a wall formation to catch the wind on a flat world with transformers to step of the voltage to something where wires could carry it long distances.

- unlike lights, fan motors are very weird when it comes to lifetime, a fan motor could fail tomorrow or it could go for 20 years. In-game when a fan is crafted, when it is crafted, the life should be set to be randomly preset to follow a bell-shaped curve for lifetime with most to have a 50% of being an average lifetime and the other 25% to be a very short life and the other 25% to be a very long life.

**Comment by Grissess** [comment]
Forge's "gaseous" fluids are a bit clunky: they're basically liquids, but instead of propagating "down" (-Y), they propagate "up" (+Y). A real gas _disperses_, and (barring reactions) multiple gases can be in a simple mixture determined by their partial pressures. 

Incidentally, one of the best places I've seen this implemented is in SS13/BS12, where each tile has a map from gas to partial pressure, and the total pressure drives diffusion. It's a 2D tile-based game and not known for its performance. "Oxygen Not Included" tries for the same aesthetic, but has some important limitations (including not allowing such mixtures).

Given at least the extra dimension, I'm not sure Minecraft's engine is ready for this. At the very least, such a large overhaul might best be separated into another mod. And doing the "simpler" thing--making Forge "gaseous" fluids--is probably just going to result in annoying fluid spam (of the kind you'd expect from griefing).

I'm open to ideas that make it more plausible, nonetheless.

**Comment by mario2582** [comment]
@Grissess - a Gases mod has already been created for Minecraft. 

Another use for fans would be to bring ventilation underground where nasty gases could naturally generate.

https://www.youtube.com/watch?v=5H7r-n_mfdw

**Comment by jrddunbr** [comment]
Considering the port is starting and this is nontrivial to code and for performance, I'm shooting this down. Make another mod and we might integrate in the future.
