### ISSUE TITLE
CCT not copying copper cables or casings

### ISSUE THREAD

**Issue by dennis-qt** [jrddunbr/ElectricalAge#210]
When trying to copy a config of a vDC/DC, neither copper cables nor the casing are being copied. This is not limited to the vDC/DC only, since when doing the same with regular DC/DCs, the casing isn't copied as well.

**Comment by Grissess** [comment]
I think casings may have been a feature I was unaware of when I made the CCT, not to mention that a test for its existence is [one sneaky line](https://github.com/jrddunbr/ElectricalAge/blob/a11f6ebc4b6433164d0d422093ce441be1f323a3/src/main/java/mods/eln/transparentnode/transformer/TransformerElement.java#L297) in the element that I overlooked.

Not moving copper cables likely has to do that they aren't "cables" in the code. Someone changed that, apparently, and that offends [this function](https://github.com/jrddunbr/ElectricalAge/blob/a11f6ebc4b6433164d0d422093ce441be1f323a3/src/main/java/mods/eln/item/ConfigCopyToolDescriptor.java#L46) which expects to find the "cable descriptor" in the SixNode registry. Since copper cables can't be placed in world (yet), they don't appear there. Thus, I see two potential fix paths here:

1. Modify that function, ad hoc, to accept copper cables for these inventories as well, or
2. Add user-placeable copper cables.

Thoughts on approach?

**Comment by dennis-qt** [comment]
I may have found a third option [inside the vDC/DC code](https://github.com/jrddunbr/ElectricalAge/blob/a11f6ebc4b6433164d0d422093ce441be1f323a3/src/main/java/mods/eln/transparentnode/variabledcdc/VariableDcDc.kt#L370-L373) itself. From what I understand it tells the CCT that tere is a cable inside those slots when it's not a real cable to the code itself. I suppose changing readCableType to readGenDescriptor might work? Same with lines 379 and 380.

**Comment by jrddunbr** [comment]
1. I don't see reason to make copper cable placable right now.
