### ISSUE TITLE
Phantom energy flow and unexplainable explosions

### ISSUE THREAD

**Issue by PlayGuye** [jrddunbr/ElectricalAge#218]
Hello, I've got an issue that involves there being a sort of energy flow I cannot explain. I'll give an example:
I have a large 164 kWp solar farm with battery storage made out of 144 (36 series, 4 parallel) ''experimental batteries'' that can (or would be able to if it weren't for the bugs) charge/discharge at up to 288 kW and can store 69120 KJ ( or 1152 kWh).
![2020-08-08_20 49 46](https://user-images.githubusercontent.com/69399960/89717680-3c2d4b80-d9b9-11ea-958c-87cbcb6a29a8.png)
The solar panels are connected as evenly as possible to avoid some making more energy than others.
![2020-08-08_20 50 05](https://user-images.githubusercontent.com/69399960/89717693-67179f80-d9b9-11ea-8fb2-9ad91875b175.png)
Same goes for the batteries.
![2020-08-08_20 51 21](https://user-images.githubusercontent.com/69399960/89717699-75fe5200-d9b9-11ea-9f2f-0bd248f6df6d.png)
The whole system runs on 3.78 kV nominal.
![2020-08-08_20 51 56](https://user-images.githubusercontent.com/69399960/89717727-8d3d3f80-d9b9-11ea-98ed-bd265afdd876.png)
But there seems to be some energy hanging around in the cables, even if they lead to a dead-end and it's nighttime.
![2020-08-08_20 52 19](https://user-images.githubusercontent.com/69399960/89717757-beb60b00-d9b9-11ea-9194-59cb0ca307c2.png)
This is what's left of my substation that exploded when I was disconnecting 6 furnaces (that then also mysteriously exploded, even though the switch to them + the batteries was off and launched me ~100 blocks into the air). I had them for a quick-discharging test (72 kW) that also exploded my batteries after I loaded the furnaces up and flipped the switch on.
Another instance of a mysterious explosion was when I was trying to fix that phantom energy thing: So I was digging the creative cables out and putting them back in near my solar panels when all of a sudden, BOOM! It was at nighttime and nothing should've been flowing through there or even exploding.

**Comment by AMIDIBOSS** [comment]
Solar panels have a bit of capacitance. That adds up to a lot if you have many solar panels (yes it's a "bug"). Treat them like they have integrated batteries. Another issue you're dealing with (another bug) is a thing called "temperature watchdog" that's supposed to explode/destroy components when they're too hot. However, when you have a lot of eln things in your world your devices might overheat and cool down, but the watchdog be like "that's supposed to be explored couple minutes ago" and it blows your stuff up seemingly for no reason. I'd recommend you disable explosions. One headache less.

**Comment by jrddunbr** [comment]
That last picture - there's no energy in there. 0V and 0A and 0W means that there is no power transfer, nor power potential in that spot. Everything rests at 20 degrees C, so that's perfectly normal.

Likely the furnaces exploded because they have virtually zero resistance and connect to ground on their first tick. They tend to cause a lot of problems when you are trying to draw lots of energy - use relays to turn them on if you're using them to load test.

Solar panels don't have capacitance, they are a simple voltage source. Connecting them together can cause some interesting results, but mostly it's because of race conditions in the old code.

The thermal sim is perfectly fine, and it will delay block destroys for two *sim* ticks. If the simulator is running slowly, it may take a moment for it to react - the sim ticks are timed with the Minecraft TPS so if your TPS is terrible, obviously it's going to take a little bit longer for things to explode. But they do not explode randomly - only when there's a spike of current. Which, unfortunately, the furnaces can cause.

Since you are also using the creative cables, I bet that the combination of their low resistance plus what I bet is a very high matrix size, you probably have some singular matrices and other issues that are plauging your world. If you're running 1.15.x or newer, run `eln matrix` and send me the file that it creates in your .minecraft folder (called `elnDumpSubSystems.txt`)

All of this said, I'm not supporting the old sim since we're working on new code and bugfixes for the old code are causing more problems than they solve; it's "easier" to rewrite the thing from scratch correctly. But we've got a lot of work ahead of us.

**Comment by PlayGuye** [comment]
> That last picture - there's no energy in there. 0V and 0A and 0W means that there is no power transfer, nor power potential in that spot. Everything rests at 20 degrees C, so that's perfectly normal.

See that image of a cable above the last image? That eventually leads to the last image's cables (It's across a road). There is reportedly some ''energy'' present inside a part of a cable that leads to a dead-end.

Where do I find ''eln matrix''?

**Comment by jrddunbr** [comment]
It's a command that you can run ingame. You just type `/eln matrix` and upload the output.

Sounds like that issue you're having is caused by a matrix condition issue in the creative cables. I'm honestly not too surprised.

**Comment by PlayGuye** [comment]
> It's a command that you can run ingame. You just type `/eln matrix` and upload the output.
> 
> Sounds like that issue you're having is caused by a matrix condition issue in the creative cables. I'm honestly not too surprised.

Alright, I typed it in and it said:
There are 455 subsystems
Average subsystem size: 6
Just to give you an idea how large my grid is, this is an image of my world:
![2020-08-09_19 49 48](https://user-images.githubusercontent.com/69399960/89738541-cfc65100-da79-11ea-861e-46e013da9263.png)
And here's the file:
[elnDumpSubSystems.txt](https://github.com/jrddunbr/ElectricalAge/files/5048166/elnDumpSubSystems.txt)

**Comment by jrddunbr** [comment]
It's probably not a half bad idea. It looks like you have one or two matricies that are really large and then a bunch of small ones, so I bet that one of those creative cable networks is the issue. Beyond breaking it up and avoiding creative cables, I don't have any other proposed fixes and we're not going to be writing code fixes anymore for this version.
