### ISSUE TITLE
Some things are not translated

### ISSUE THREAD

**Issue by KirillAldashkin** [jrddunbr/ElectricalAge#251]
I translated almost all the lines in the "en_US.lang" file (I only skipped 3-4 lines; I'm doing a Russian translation), but a large amount of content was not translated.

I attach:
1) [My .lang file](https://github.com/jrddunbr/ElectricalAge/files/5867410/new_ru.txt) (changed the extension to .txt, as GitHub does not accept .lang files)
2) [An archive with screenshots](https://github.com/jrddunbr/ElectricalAge/files/5867392/pics.zip) of untranslated things (62 screenshots, and this is a little more than half).

**Comment by KirillAldashkin** [comment]
I'll send the rest as soon as I have time.

**Comment by jrddunbr** [comment]
Some of these will be more difficult to fix than others. Namely, the "Info" stuff at the top is actually an override by Utils, which doesn't talk to the translation code because it's in the sim. I'll have to make an override in the classes that inherit from Node to fix that. I also am not sure how we want to go about tooltip text that is relatively long; I guess we just translate line by line.
