### ISSUE TITLE
Creative Tabs

### ISSUE THREAD

**Issue by jrddunbr** [jrddunbr/ElectricalAge#85]
Need more creative tabs to split stuff out. There's sooo much stuff in Eln.

**Comment by jrddunbr** [comment]
If anyone has any suggestions about how to organize the items, or graphics for tabs, let me know.

**Comment by Silfryi** [comment]
Three tabs: Shaft stuff, Cables'n stuff, machines/etc

**Comment by jrddunbr** [comment]
Anything more specific?

**Comment by Silfryi** [comment]
IE: 
Shaft stuff:
1. Motors
2. Shafts (Clutches, Joints, Hubs, Tachometers)
3. Turbines (Gas/Steam)
Cables n' Stuff
1. Cables (low through vhigh voltage + signal)
2. Control Devices (Relays, Diodes, Probes, etc)
3. Processing ( Schmitt triggers, sigprocs, NOT chips)
4. Transformers and Cores
5. T1 and T2 poles and transformers
Machines
1. 50 & 200V macerator, compressor, etc
2. 800V machines (Teleporter, Miner, Arc Furnace)
3. Furnace and coils
Materials (New tab since last time)
1. All raw materials (Copper, tungsten)
2. All Dusts (Silicon, iron, copper)
3.Ingots (Arc Clay, etc)

**Comment by jrddunbr** [comment]
As it turns out, I need to rewrite the mod registration classes for this to ever work. Postponing.
